# Generated by Django 5.0.4 on 2024-05-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="position",
            name="duties",
            field=models.TextField(blank=True, null=True),
        ),
    ]
