# Generated by Django 4.2.11 on 2024-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_worker_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="worker_photos/"),
        ),
    ]
