# Generated by Django 4.2.11 on 2024-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_alter_worker_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="image_file",
        ),
    ]
