# Generated by Django 4.2.11 on 2024-05-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0006_alter_worker_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="duties",
        ),
    ]
